### ISSUE TITLE
Annotation @flag not allowed for type Atom

### ISSUE THREAD

**Issue by derhedwig** [holidaypirates/nucleus#13]
nucleus-styleguide: 1.0.4
node: 4.5.0
npm: 2.15.9

Hi!
It seems like the @flag Annotation is only supported for Structures, despite the [Annotation Reference](https://holidaypirates.github.io/nucleus/annotation-reference.html) giving an example for Atoms.

The following example
```
/**
 * @atom betabanner
 * @flag full-width
*/
```
results in the following warning:
```
Take care! Annotation @flag not allowed for type Atom of .betabanner in [...]
 Valid annotations are @atom, @section, @description, @markup, @deprecated. This
 element will not appear in the final StyleGuide until you fix this error.
```

I also peeked into [Atom.js](https://github.com/holidaypirates/nucleus/blob/master/src/entities/Atom.js) in master and it also doesn't seem to support this:
```
this.fillable = ['atom', 'section', 'description', 'markup', 'deprecated'];
```

**Comment by michaelseibt** [comment]
Hi @derhedwig, you are right. Only structures and molecules are having flags at the moment.

Originally, with just the "full-width" flag, we did not consider to add flags to atoms because it might be tempting to mark more complex elements (more than one HTML element) as atoms. 

Basically we also never encountered a situation where it would be handy to span an atom to full width. But of course the practical use-case is always different. 

Now with more flags to come in the future, it will surely make sense to allow flags for atoms, too. I'll keep this in mind for one of the future updates.

As always, thanks for your contribution.

**Comment by derhedwig** [comment]
Hi @michaelseibt!
Okay. I was just confused, because I thought I was reading an example in the docs with an atom having a flag. So, I thought, it wasn't intentional. But now I can't find it in the docs anymore.
And now, that I read your reply, I'm actually thinking about making my banner a molecule or structure.
