### ISSUE TITLE
Question: Third-party preprosessor needed for preview styles?

### ISSUE THREAD

**Issue by trollsyn** [holidaypirates/nucleus#7]
Hi, I have a question about preview styles:

I am not sure if I have understood the demo files correctly, but it seems that we need to set up our own preprosessor for the preview styles?

For example, if I make an atom for buttons like so:
```/**
 * @atom Success
 * @section Buttons
 * @description
 *  Something something buttons.
 * @markup
 *  <button class="my-success">.my-success</button>
  */
.my-success {
	background-color: pink;
}
```
This would give me a nice starting point for the "Buttons" section along with a code example in my styleguide.

However, I don't see the preview styles (i.e. pink background color on the button) since the CSS code above is just shown for reference. If I want to actually load preview styles, I have to include the same CSS again and put in in a stylesheet somewhere and use the `"css": "../path-tos/my-preview-styles.css"` option in `config.nucleus.json`.

This means I need to maintain styles in 2 different files (styleguide content + preview styles), and also set up tasks for a Sass-preprosessor of my own choice, like grunt or gulp.

Is this how it works or have I missed something here about the preview styles?

**Comment by michaelseibt** [comment]
Hi trollsyn!

Yes, you are right. Nucleus does not replace or assume anything about your build chain. 

Essentially this means that you pass in the "raw" style sources to Nucleus in order to get the style guide information, and on the other hand side, to get the preview properly working, you provide the "final" css file.

I agree that it's not efficient to maintain two files, so indeed - using a build script is recommended.

Hope this helped!
